import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { MyProvider } from "@/context/StoreContext";

export const metadata = {
  title: "ToDoNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen">
        <Provider>
          <MyProvider>
          <Navbar />
          {children}
          </MyProvider>
        </Provider>
      </body>
    </html>
  );
}
