import "./globals.css";

export const metadata = {
  title: "ToDoNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-primary to-secondary min-h-screen">{children}</body>
    </html>
  );
}
